apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: %SIDB_NAME%
  namespace: %SIDB_NAMESPACE%
spec:

  ## DB edition
  edition: free
  ## Use only alphanumeric characters for sid
  sid: FREE

  ## Secret containing SIDB password mapped to secretKey
  adminPassword:
    secretName: %SIDB_ADMIN_PWD_SECRET%

  ## Database Image
  image:
    pullFrom: container-registry.oracle.com/database/free:latest
    prebuiltDB: false

  ## Persistence is optional for prebuilt DB image
  ## if specified, the prebuilt DB datafiles are copied over to the persistant volume before DB startup
  persistence:
   size: 50Gi
   storageClass: "oci-bv"
   accessMode: "ReadWriteOnce"

  ## Count of Database Pods.
  replicas: 1