DROP TABLE TODOITEM;
CREATE TABLE TODOITEM (
  ID NUMBER GENERATED ALWAYS AS IDENTITY,
  DESCRIPTION VARCHAR2(32000),
  CREATION_TS TIMESTAMP WITH TIME ZONE DEFAULT ON NULL CURRENT_TIMESTAMP,
  DONE NUMBER(1, 0) DEFAULT 0,
  PRIMARY KEY (ID)
);
INSERT INTO TODOITEM (DESCRIPTION) VALUES ('Very first item');