CREATE TABLE TODOOWNER.TODOITEM
(
    ID          NUMBER GENERATED ALWAYS AS IDENTITY,
    DESCRIPTION VARCHAR2(4000),
    CREATION_TS TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    DONE        NUMBER(1, 0)             DEFAULT 0,
    PRIMARY KEY (ID)
);

INSERT INTO TODOOWNER.TODOITEM (DESCRIPTION)
VALUES ('My first task!');