spring.application.name=MyTodoList
spring.threads.virtual.enabled=true

# COHERE command-r
#https://txt.cohere.com/command-r/
spring.ai.ollama.base-url=http://<COHERE_MODEL_SERVER_IP>:11434
spring.ai.ollama.embedding.options.model=command-r
spring.ai.ollama.chat.options.model=command-r

spring.datasource.url=jdbc:oracle:thin:@<TODO_PDB_NAME>_tp?TNS_ADMIN=/mtdrworkshop/creds
spring.datasource.username=VECTOR_USER
spring.datasource.password=<VECTOR_USER_PASSWORD>

# Spring AI - Oracle Universal Connection Pool (UCP)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

##Logging properties for UCP
logging.level.root=info
logging.file.name=logs.log
logging.level.oracle.ucp=info

security.ignored=/**
spring.security.enabled=false
management.security.enabled=false
security.basic.enabled=false