
# Set for local testing
#spring.datasource.url=${database.url}
#spring.datasource.username=${database.user}
#spring.datasource.password=${database.password}

# Set for local testing
#spring.security.user.name=${security.user}
#spring.security.user.password=${security.password}

# Properties of UCP
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

# Enable JPA
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#
## Logging properties
logging.level.root=DEBUG
logging.file.name=logs.log
#logging.level.oracle.ucp=trace
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE




