## MyToDoReact version 2.0.0
##
## Copyright (c) 2024 Oracle, Inc.
## Licensed under the Universal Permissive License v 1.0 as
## shown at https://oss.oracle.com/licenses/upl/

apiVersion: v1
kind: Service
metadata:
  name: todolistapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: todolistapp

  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp
  labels:
    app: todolistapp
spec:
  selector:
    matchLabels:
      app: todolistapp
  replicas: 2
  template:
    metadata:
      labels:
        app: todolistapp
    spec:
      containers:
        - name: todolistapp-springboot
          image: %DOCKER_REGISTRY%/todolistapp-springboot:0.1
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: "jdbc:oracle:thin:@%TODO_PDB_NAME%_tp?TNS_ADMIN=/mtdrworkshop/creds"
            - name: DATABASE_USER
              value: "admin"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbuser
                  key: dbpassword
                  optional: true

            - name: SPRING_SECURITY_USER_NAME
              value: "%UI_USERNAME%"
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frontendadmin
                  key: password
                  optional: true

          volumeMounts:
            - name: creds
              mountPath: /mtdrworkshop/creds
          ports:
            - containerPort: 8080

      restartPolicy: Always
      volumes:
        - name: creds
          secret:
            secretName: db-wallet-secret
