#!/bin/bash
## MyToDoReact version 1.0.
##
## Copyright (c) 2021 Oracle, Inc.
## Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/
export k8s_pod=$1
for line in $(kubectl get pods --all-namespaces | grep $k8s_pod | awk '{print $2}'); do
    echo "kubectl port-forward $line -n mtdrworkshop 8080:8080 "
    kubectl port-forward $line -n mtdrworkshop 8080:8080
done
